print("##############################")
print("#                            #")
print("#   Muhammad Dani Maulana    #")
print("#        2510817110012       #")
print("#                            #")
print("##############################")